

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t44-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  tls:
  - hosts:
    - api44.my-points.ru
    - web44.my-points.ru
    - insights44.my-points.ru
    secretName: serverpod-tls-t44
  rules:
  - host: "api44.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t44-server-service
            port:
              name: api
  - host: "web44.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t44-server-service
            port:
              name: web
  - host: "insights44.my-points.ru"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: t44-server-service
            port:
              name: insights
    